### PR TITLE
Popup 2.0

### PR DESCRIPTION
**Pull request by Ramaunspoken**
Created the Popup with Bootstrap, html, css and js.
Added the font-family Poppins to all code.

### CODE REVIEW

**Comment by bellom** [comment]
@Ramaunspoken

### This is a manual review

Note: It will be approved on your dashboard as soon as possible.

## Request Changes 

Kindly replicate the Figma design:

Figma design:
image


Your Design:
image

Once done, reply here.

Cheers and Happy coding!

**Comment by bellom** [comment]
@Ramaunspoken - You're yet to fix the issue, you only updated your README file.

**Comment by bellom** [comment]
> @Ramaunspoken
> 
> ### This is a manual review
> Note: It will be approved on your dashboard as soon as possible.
> 
> ## Request Changes
> Kindly replicate the Figma design:
> 
> Figma design: image
> 
> Your Design: image
> 
> Once done, reply here.
> 
> Cheers and Happy coding!

@Ramaunspoken - kindly work on this request change.

**Comment by Ramaunspoken** [comment]
@bellom - There is no error on my side I can't see any error.
image
Screenshot (68)
Check the Live link Please and see : https://ramaunspoken.github.io/Popup-3/

**Comment by bellom** [comment]
@Ramaunspoken - Share with me a loom video and try to reload the page, thank you.

**Comment by Ramaunspoken** [comment]
https://www.loom.com/share/ef8d706fbfda4a68b2fe0ae285c2e30b

**Comment by bellom** [comment]
@Ramaunspoken - kindly push your last commit. You have Alexandra as name, not Rama.

**Comment by bellom** [comment]
@Ramaunspoken - Kindly create a new loom video and run your project locally, do not use a live demo, that way, we will be sure you already push your last changes, thank you.

**Comment by Ramaunspoken** [comment]
This is the Local view
https://www.loom.com/share/3c149eb4d527474e963946bbc84e19b3

**Comment by bellom** [comment]
@Ramaunspoken - For some reason, we tested your local code and it doesn't reflect what you have on the loom.

kindly run this command to double-check:
`git diff`
`git log`

**Comment by bellom** [comment]
@Ramaunspoken - kindly fix the conflict.

**Comment by bellom** [comment]
@Ramaunspoken - go ahead and merge, we will check for plagiarism afterward.

**Pull request merged**
